.TH WORDRANK 1
.SH NAME
wordrank \- Determine a word's alphabetical rank
.SH SYNOPSIS
.B wordrank
.IR STRING
.SH DESCRIPTION
For every string S, there are n other permutations of S. If all of those
permutations were put in alphabetical order, then S would fall under
a certain rank in that order. wordRank.c determines which rank that is.
.PP
For example, AB would fall under rank 1, BA would fall under rank 2.
